### ISSUE TITLE
Line calculation issues with v1.2.0

### ISSUE THREAD

**Issue by drbrain** [evanphx/kpeg#45]
With this grammar + support code:

```kpeg
%% name = Bug

%% {
  attr_reader :parsed
  alias parsed? parsed

  def self.test
    expander = self.new "${name}"
    expander.parse

    # ↓↓↓ this line shows the bug
    expander.raise_error unless expander.parsed?
    # ↑↑↑

    expander.result
  end

  def initialize(string)
    @string = string
    @parsed = nil

    super @string
  end

  def parse
    @parsed = super
  end
}

root = variable

variable = "$" variable_name

variable_name = < /\w+/ >
```

When compiled with kpeg 1.1.0 I get a ParseError as I expect:

```
$ kpeg _1.1.0_ -f -o bug.rb bug.kpeg && ruby -I /usr/local/lib/ruby/gems/2.6.0/gems/kpeg-1.1.0/lib -r ./bug -e Bug.test
Wrote Bug to bug.rb
/usr/local/lib/ruby/gems/2.6.0/gems/kpeg-1.1.0/lib/kpeg/compiled_parser.rb:109:in `raise_error': @1:2 failed rule 'variable_name', got '{' (KPeg::CompiledParser::ParseError)
	from /Users/erichodel/tmp/kpeg-1.2.0-bug/bug.rb:13:in `test'
	from -e:1:in `<main>'
```

With kpeg 1.2.0 I get a NoMethodError instead:

```
$ kpeg _1.2.0_ -f -o bug.rb bug.kpeg && ruby -r ./bug -e Bug.test
Wrote Bug to bug.rb
/usr/local/lib/ruby/gems/2.6.0/gems/kpeg-1.2.0/lib/kpeg/compiled_parser.rb:95:in `failure_oneline': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.6.0/gems/kpeg-1.2.0/lib/kpeg/compiled_parser.rb:109:in `raise_error'
	from /Users/erichodel/tmp/kpeg-1.2.0-bug/bug.rb:13:in `test'
	from -e:1:in `<main>'
```

The error comes from [KPeg::CompiledParser#failure_online](https://github.com/evanphx/kpeg/blob/99281c0647a8b413b7302b0e68185ae960178203/lib/kpeg/compiled_parser.rb#L96). I only have one line here `lines[0]`, but `l` is 2 for some reason (`lines[1]`) so this gives NoMethodError due to some sort of off-by-one.

**Comment by drbrain** [comment]
Peeking inside [KPeg::Position#current_line](https://github.com/evanphx/kpeg/blob/99281c0647a8b413b7302b0e68185ae960178203/lib/kpeg/position.rb#L14-L26)

For `@line_offsets` I have `[-1, 0, 7]`

For `target` (from `@failing_rule_offset`) I have `1` (the `{` character)

`[-1, 0, 7].bsearch_index {|x| x >= 1 }` => `2` which is one line too far

I think the `x >= target` for the [new `bsearch_index`](https://github.com/evanphx/kpeg/blob/99281c0647a8b413b7302b0e68185ae960178203/lib/kpeg/position.rb#L25) is adding an extra line compared to the [old method](/evanphx/kpeg/blob/99281c0647a8b413b7302b0e68185ae960178203/lib/kpeg/position.rb#L35). If I'm reading this right the new method picks the line index after the character position has been passed, while the old method picks the line index that the character position just passed.

PS: I'm unsure if kpeg's position reference (@L:C) are zero or one based
