### ISSUE TITLE
non existing files cause error during `gem build`

### ISSUE THREAD

**Issue by Segaja** [evanphx/kpeg#51]
While executing `gem build kpeg.gemspec` I see this error:

```
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    [".gemtest", ".travis.yml"] are not files
        /usr/lib/ruby/3.0.0/rubygems/specification_policy.rb:478:in `error'
        /usr/lib/ruby/3.0.0/rubygems/specification_policy.rb:298:in `validate_non_files'
        /usr/lib/ruby/3.0.0/rubygems/specification_policy.rb:73:in `validate_required!'
        /usr/lib/ruby/3.0.0/rubygems/specification_policy.rb:44:in `validate'
        /usr/lib/ruby/3.0.0/rubygems/specification.rb:2635:in `validate'
        /usr/lib/ruby/3.0.0/rubygems/package.rb:298:in `build'
        /usr/lib/ruby/3.0.0/rubygems/package.rb:136:in `build'
        /usr/lib/ruby/3.0.0/rubygems/commands/build_command.rb:99:in `build_package'
        /usr/lib/ruby/3.0.0/rubygems/commands/build_command.rb:89:in `build_gem'
        /usr/lib/ruby/3.0.0/rubygems/commands/build_command.rb:69:in `execute'
        /usr/lib/ruby/3.0.0/rubygems/command.rb:323:in `invoke_with_build_args'
        /usr/lib/ruby/3.0.0/rubygems/command_manager.rb:185:in `process_args'
        /usr/lib/ruby/3.0.0/rubygems/command_manager.rb:149:in `run'
        /usr/lib/ruby/3.0.0/rubygems/gem_runner.rb:51:in `run'
        /usr/bin/gem:13:in `<main>'
```

When I remove the two listed files from line 15 of the `kpeg.gemspec` file it works.

**Comment by evanphx** [comment]
This is now fixed!
